name: CI

# On every pull request, but only on push to master
on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:
env:
  LATEST_PY_VERSION: '3.9'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags') && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.LATEST_PY_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flit
          python -m pip install .

      - name: Set tag version
        id: tag
        # https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set module version
        id: module
        # https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
        run: echo ::set-output name=version::$(python -c 'from importlib.metadata import version; print(version("timvt"))')

      - name: Build and publish
        if: steps.tag.outputs.tag == steps.module.outputs.version
        env:
          FLIT_USERNAME: ${{ secrets.PYPI_USERNAME }}
          FLIT_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: flit publish

  publish-docker:
    needs: [tests]
    if: github.ref == 'refs/heads/master' || startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag version
        id: tag
        # https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      # Push `latest` when commiting to master
      - name: Build and push
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: dockerfiles/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest

      # Push `{VERSION}` when pushing a new tag
      - name: Build and push
        if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: dockerfiles/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }}
